#!/usr/bin/env python3
"""Screen-record the LIVE Cinemory app doing the real thing.

Drives https://cinemory-...run.app in the SYSTEM Chrome (``channel="chrome"`` —
no browser download, the disk is tight) at 1920x1080 and records the whole
journey to a WebM: landing -> add photos -> pick an occasion -> generate ->
poll the live job -> the reel plays -> open Provenance -> press Verify.

Nothing is mocked. The reel that plays is generated by the deployed service,
by Genblaze/Kling on GMI Cloud, from the committed anniversary demo photos.

Why only TWO photos: the pipeline runs one live Kling image-to-video call per
photo and a single call measured ~314s against the live service, while the
frontend's poll ceiling is 12 minutes (``REEL_JOB_MAX_POLL_MS`` in
``frontend/src/lib/queries.ts``). Two photos (~10.5 min) is the most that fits
inside the ceiling, so it is the most the product can be shown doing for real
in one continuous take. Three would trip the honest "taking longer than
expected" degrade instead of showing a reel.

Writes next to the video a ``.marks.json`` of milestone timestamps measured
from the first recorded frame, so ``build-video.py`` can cut exact segments
without anyone eyeballing a scrubber.

Usage:
  python demo/capture-live.py [--out DIR] [--base URL]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHOTOS = os.path.join(REPO, "sample-data", "anniversary")
BASE = "https://cinemory-595784992266.europe-west1.run.app"

# The two photos uploaded in the take (see the module docstring for why two).
UPLOAD = ["03-the-toast.jpg", "06-end-of-the-night.jpg"]

#: Each footage beat is cut from the span between two marks, and that span has
#: to be at least as long as the beat's narration or the picture would have to
#: freeze on its last frame to fill the line. Each floor is that beat's measured
#: duration in ``demo/cinemory-demo.beats.json`` plus ``cut-footage.py``'s 0.5s
#: headroom, rounded up. Checked at the end of the take so a too-quick capture
#: fails HERE, loudly, instead of quietly becoming a frozen frame in the
#: finished video. Re-derive these whenever a narration line changes length.
PHASE_FLOOR: list[tuple[str, str, str, float]] = [
    ("02-photos", "landing", "step2_open", 13.7),
    ("03-occasion", "step2_open", "generate_clicked", 12.9),
    ("04-rolling", "generate_clicked", "reel_ready", 16.7),
    ("05-reel", "reel_playing", "reel_played", 10.4),
    # +2.3s because cut-footage.py starts this cut late (see its CUTS table).
    ("06-verify", "provenance_open", "verified_read", 21.4),
]

# Capture at the FINAL delivery resolution with a 2x device pixel ratio: the CSS
# layout is the real 1280-wide desktop layout (so type is at its native size and
# stays legible in the finished 720p video) while the page is rasterised at
# 2560x1440 and downsampled into the recording, which keeps the text crisp.
# Recording at 1920x1080 and scaling down later shrinks every glyph by a third
# and the UI copy stops being readable.
W, H = 1280, 720
DPR = 2


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(REPO, "demo", ".capture"))
    ap.add_argument("--base", default=BASE)
    ap.add_argument("--dry-run", action="store_true",
                    help="walk every selector up to (not including) Generate, "
                         "then quit — validates the take without a 10-minute live job")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    from playwright.sync_api import sync_playwright

    marks: list[dict] = []
    t0 = 0.0

    def mark(name: str) -> None:
        el = time.time() - t0
        marks.append({"name": name, "t": round(el, 2)})
        print(f"[mark] {el:8.2f}s  {name}", flush=True)

    with sync_playwright() as pw:
        browser = pw.chromium.launch(channel="chrome", headless=False,
                                     args=["--hide-scrollbars"])
        ctx = browser.new_context(
            viewport={"width": W, "height": H},
            record_video_dir=args.out,
            record_video_size={"width": W, "height": H},
            device_scale_factor=DPR,
        )
        page = ctx.new_page()
        page.set_default_timeout(60_000)
        t0 = time.time()          # recording starts with the context/page
        mark("record_start")

        # ── Landing ────────────────────────────────────────────────────────
        page.goto(args.base, wait_until="networkidle")
        page.wait_for_timeout(1500)
        mark("landing")
        # a slow scroll down the landing page, then back — real screen motion
        for _ in range(9):
            page.mouse.wheel(0, 90)
            page.wait_for_timeout(70)
        page.wait_for_timeout(700)
        for _ in range(9):
            page.mouse.wheel(0, -90)
            page.wait_for_timeout(70)
        page.wait_for_timeout(800)
        mark("landing_scrolled")

        page.get_by_role("button", name="Create your reel").first.click()
        page.wait_for_timeout(2000)
        mark("step1_open")

        # ── Step 1: photos ─────────────────────────────────────────────────
        files = [os.path.join(PHOTOS, f) for f in UPLOAD]
        for f in files:
            if not os.path.exists(f):
                raise SystemExit(f"[STOP] missing demo photo {f}")
        page.set_input_files('input[type="file"]', files)
        page.wait_for_timeout(2500)
        mark("photos_added")
        to_occ = page.get_by_role("button", name="Choose an occasion")
        to_occ.wait_for(state="visible", timeout=30_000)
        # the storyboard strip sits below the drop zone — ease it into frame
        for _ in range(6):
            page.mouse.wheel(0, 70)
            page.wait_for_timeout(80)
        page.wait_for_timeout(3000)
        mark("storyboard_held")
        to_occ.click()
        page.wait_for_timeout(2200)
        mark("step2_open")

        # ── Step 2: occasion ───────────────────────────────────────────────
        # Dwells here are deliberately long: this phase must supply at least as
        # many seconds of picture as beat 03's narration needs (see PHASE_FLOOR).
        page.wait_for_timeout(2600)
        anniversary = page.get_by_role("radio", name="Anniversary").first
        anniversary.scroll_into_view_if_needed()
        page.wait_for_timeout(1600)
        # let the eye travel the six occasion cards before one is chosen
        for _ in range(4):
            page.mouse.wheel(0, 55)
            page.wait_for_timeout(160)
        page.wait_for_timeout(1400)
        for _ in range(4):
            page.mouse.wheel(0, -55)
            page.wait_for_timeout(160)
        page.wait_for_timeout(1200)
        anniversary.click()
        page.wait_for_timeout(4200)
        mark("occasion_picked")
        gen = page.get_by_role("button", name="Generate my reel")
        gen.scroll_into_view_if_needed()
        page.wait_for_timeout(2600)
        if args.dry_run:
            gen.wait_for(state="visible", timeout=15_000)
            print("[dry-run] every selector up to Generate resolved. Not submitting.")
            ctx.close()
            browser.close()
            return 0
        gen.click()
        mark("generate_clicked")

        # ── Step 3: the live job ───────────────────────────────────────────
        page.wait_for_timeout(12_000)          # capture the progress UI moving
        mark("polling_held")

        # Wait for the result step. The job is live: ~5.2 min per photo.
        result_heading = page.get_by_role("heading", name="Your reel is ready")
        result_heading.wait_for(state="visible", timeout=13 * 60_000)
        page.wait_for_timeout(2500)
        mark("reel_ready")

        # ── Step 4: the reel plays ─────────────────────────────────────────
        # The <video> only mounts once the result step has finished animating in,
        # and it needs its source loaded before play() will do anything. Take 1
        # nudged too early, the element did not exist yet, and the beat recorded
        # a paused player sitting at 0:00. So: wait for the element, wait for it
        # to be readable, THEN play, then prove it is actually advancing.
        page.wait_for_selector("video", state="attached", timeout=60_000)
        page.wait_for_function(
            "() => { const v = document.querySelector('video');"
            "        return v && v.readyState >= 2; }", timeout=90_000)
        page.evaluate(
            """() => { const v = document.querySelector('video');
                       v.muted = true; v.currentTime = 0; return v.play(); }"""
        )
        page.wait_for_timeout(1200)
        playing = page.evaluate(
            "() => { const v = document.querySelector('video');"
            "        return { t: v.currentTime, paused: v.paused, dur: v.duration }; }")
        print(f"[reel] {playing}")
        if playing["paused"] or playing["t"] <= 0:
            print("[warn] the reel did not start playing; beat 05 would be a still")
        mark("reel_playing")
        page.wait_for_timeout(13_000)          # let the reel actually play
        mark("reel_played")

        # ── Provenance + Verify ────────────────────────────────────────────
        prov = page.get_by_role("heading", name="Provenance").first
        prov.scroll_into_view_if_needed()
        page.wait_for_timeout(3000)
        mark("provenance_open")
        for _ in range(8):                      # slow read down the panel
            page.mouse.wheel(0, 100)
            page.wait_for_timeout(170)
        page.wait_for_timeout(3200)
        mark("provenance_scrolled")

        verify = page.get_by_role("button", name="Verify provenance").first
        verify.scroll_into_view_if_needed()
        page.wait_for_timeout(2200)
        verify.click()
        page.wait_for_timeout(7000)
        mark("verified")
        for _ in range(5):
            page.mouse.wheel(0, 100)
            page.wait_for_timeout(170)
        page.wait_for_timeout(6000)
        mark("verified_read")

        total = time.time() - t0
        print(f"[capture] finished in {total:.1f}s", flush=True)

        video = page.video
        vpath = video.path() if video else None
        ctx.close()          # flushes the video file
        browser.close()

    if not vpath or not os.path.exists(vpath):
        raise SystemExit("[STOP] no video was written")
    final = os.path.join(args.out, "journey.webm")
    if os.path.abspath(vpath) != os.path.abspath(final):
        if os.path.exists(final):
            os.remove(final)
        os.replace(vpath, final)
    with open(os.path.join(args.out, "journey.marks.json"), "w", encoding="utf-8") as fh:
        json.dump({"video": "journey.webm", "base": args.base,
                   "uploaded": UPLOAD, "marks": marks}, fh, indent=2)
        fh.write("\n")
    print(f"[ok] {final}  ({os.path.getsize(final) // 1024} KB)")
    print(f"[ok] {os.path.join(args.out, 'journey.marks.json')}")

    at = {m["name"]: m["t"] for m in marks}
    short = []
    print("phase lengths vs. what each beat needs:")
    for beat, a, b, floor in PHASE_FLOOR:
        if a not in at or b not in at:
            short.append(f"{beat}: missing mark {a if a not in at else b}")
            continue
        span = at[b] - at[a]
        ok = span >= floor
        print(f"  [{'OK  ' if ok else 'SHORT'}] {beat:<12} {span:7.2f}s  (needs >= {floor:.1f}s)")
        if not ok:
            short.append(f"{beat}: {span:.2f}s < {floor:.1f}s")
    if short:
        print("\n[STOP] the take is too quick in places; re-shoot with longer dwells:")
        for s in short:
            print(f"  - {s}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
