#!/usr/bin/env python3
"""Screen-record the LIVE Cinemory app doing the real thing.

Drives https://cinemory-...run.app in the SYSTEM Chrome (``channel="chrome"`` —
no browser download, the disk is tight) at 1920x1080 and records the whole
journey to a WebM: landing -> add photos -> pick an occasion -> generate ->
poll the live job -> the reel plays -> open Provenance -> press Verify.

Nothing is mocked. The reel that plays is generated by the deployed service,
by Genblaze/Kling on GMI Cloud, from the committed anniversary demo photos.

Why FIVE photos: generation now runs concurrently (see
``MAX_CONCURRENT_GENERATIONS`` in ``src/cinemory/pipeline.py``, mirrored in
``frontend/src/lib/reel-budget.ts``), so a full reel is one WAVE rather than
one call after another. Five is the product's photo cap and it finishes in
~6 minutes against the frontend's 12-minute poll ceiling
(``REEL_JOB_MAX_POLL_MS``), so the take can now show the cap being used rather
than the two photos that were all a sequential pipeline could fit.

The take also RELOADS the tab mid-job. The job id is written into the URL
(``#reel/<job_id>``) the moment the job is submitted, so a reload resumes the
same live job instead of losing it. Playwright records the page viewport only,
so the address bar is never in frame: what the picture shows is the app's own
resume copy ("Picking this reel back up", "Already in progress"), which is the
in-page evidence that the reload recovered a running job. The URL itself is
recorded in the marks file and burned into the beat's caption instead.

Writes next to the video a ``.marks.json`` of milestone timestamps measured
from the first recorded frame, so ``build-video.py`` can cut exact segments
without anyone eyeballing a scrubber. The submitted job id goes in there too,
so ``GET /reels/jobs/<id>`` (which carries the per-job usage accounting) can be
read afterwards for the same run the video shows.

Usage:
  python demo/capture-live.py [--out DIR] [--base URL]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHOTOS = os.path.join(REPO, "sample-data", "anniversary")
BASE = "https://cinemory-595784992266.europe-west1.run.app"

# The five photos uploaded in the take — the product's whole cap, in the order
# they happened (see the module docstring for why five is now reachable).
UPLOAD = [
    "01-arrival.jpg",
    "02-the-table.jpg",
    "03-the-toast.jpg",
    "04-cutting-the-cake.jpg",
    "06-end-of-the-night.jpg",
]

#: Each footage beat is cut from the span between two marks, and that span has
#: to be at least as long as the beat's narration or the picture would have to
#: freeze on its last frame to fill the line. Each floor is that beat's measured
#: duration in ``demo/cinemory-demo.beats.json`` plus ``cut-footage.py``'s 0.5s
#: headroom, rounded up. Checked at the end of the take so a too-quick capture
#: fails HERE, loudly, instead of quietly becoming a frozen frame in the
#: finished video. Re-derive these whenever a narration line changes length.
#: Re-derived 2026-08-03 for the five-photo reshoot, straight from the measured
#: narration: floor = cut-footage.py's settle offset for that beat + the beat's
#: measured scene length + its 0.5s headroom, rounded up. Re-derive whenever a
#: narration line changes length.
PHASE_FLOOR: list[tuple[str, str, str, float]] = [
    ("02-photos", "landing", "step2_open", 19.8),
    ("03-occasion", "step2_open", "generate_clicked", 10.9),
    # +1.0s settle (see cut-footage.py's CUTS table).
    ("04-rolling", "generate_clicked", "reload_start", 20.7),
    ("05-link", "resumed", "resume_held", 16.6),
    ("06-reel", "reel_playing", "reel_played", 11.0),
    # +2.3s settle (see cut-footage.py's CUTS table).
    ("07-verify", "provenance_open", "verified_read", 23.5),
]

# Capture at the FINAL delivery resolution with a 2x device pixel ratio: the CSS
# layout is the real 1280-wide desktop layout (so type is at its native size and
# stays legible in the finished 720p video) while the page is rasterised at
# 2560x1440 and downsampled into the recording, which keeps the text crisp.
# Recording at 1920x1080 and scaling down later shrinks every glyph by a third
# and the UI copy stops being readable.
W, H = 1280, 720
DPR = 2


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(REPO, "demo", ".capture"))
    ap.add_argument("--base", default=BASE)
    ap.add_argument("--dry-run", action="store_true",
                    help="walk every selector up to (not including) Generate, "
                         "then quit — validates the take without a 10-minute live job")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    from playwright.sync_api import sync_playwright

    marks: list[dict] = []
    t0 = 0.0

    def mark(name: str) -> None:
        el = time.time() - t0
        marks.append({"name": name, "t": round(el, 2)})
        print(f"[mark] {el:8.2f}s  {name}", flush=True)

    with sync_playwright() as pw:
        browser = pw.chromium.launch(channel="chrome", headless=False,
                                     args=["--hide-scrollbars"])
        ctx = browser.new_context(
            viewport={"width": W, "height": H},
            record_video_dir=args.out,
            record_video_size={"width": W, "height": H},
            device_scale_factor=DPR,
        )
        page = ctx.new_page()
        page.set_default_timeout(60_000)
        t0 = time.time()          # recording starts with the context/page
        mark("record_start")

        # ── Landing ────────────────────────────────────────────────────────
        page.goto(args.base, wait_until="networkidle")
        page.wait_for_timeout(1500)
        mark("landing")
        # a slow scroll down the landing page, then back — real screen motion
        for _ in range(9):
            page.mouse.wheel(0, 90)
            page.wait_for_timeout(70)
        page.wait_for_timeout(700)
        for _ in range(9):
            page.mouse.wheel(0, -90)
            page.wait_for_timeout(70)
        page.wait_for_timeout(800)
        mark("landing_scrolled")

        page.get_by_role("button", name="Create your reel").first.click()
        page.wait_for_timeout(2000)
        mark("step1_open")

        # ── Step 1: photos ─────────────────────────────────────────────────
        files = [os.path.join(PHOTOS, f) for f in UPLOAD]
        for f in files:
            if not os.path.exists(f):
                raise SystemExit(f"[STOP] missing demo photo {f}")
        page.set_input_files('input[type="file"]', files)
        page.wait_for_timeout(3000)
        mark("photos_added")
        to_occ = page.get_by_role("button", name="Choose an occasion")
        to_occ.wait_for(state="visible", timeout=30_000)
        # the storyboard strip sits below the drop zone — ease it into frame,
        # then hold on the cap note ("a limit of this demo, not of the reel
        # maker"), which beat 02's narration is about
        for _ in range(6):
            page.mouse.wheel(0, 70)
            page.wait_for_timeout(80)
        page.wait_for_timeout(4500)
        mark("storyboard_held")
        for _ in range(5):
            page.mouse.wheel(0, -60)
            page.wait_for_timeout(90)
        page.wait_for_timeout(6200)
        mark("cap_note_held")
        to_occ.click()
        page.wait_for_timeout(2400)
        mark("step2_open")

        # ── Step 2: occasion ───────────────────────────────────────────────
        # Dwells here are deliberately long: this phase must supply at least as
        # many seconds of picture as beat 03's narration needs (see PHASE_FLOOR).
        page.wait_for_timeout(2600)
        anniversary = page.get_by_role("radio", name="Anniversary").first
        anniversary.scroll_into_view_if_needed()
        page.wait_for_timeout(1600)
        # let the eye travel the six occasion cards before one is chosen
        for _ in range(4):
            page.mouse.wheel(0, 55)
            page.wait_for_timeout(160)
        page.wait_for_timeout(1400)
        for _ in range(4):
            page.mouse.wheel(0, -55)
            page.wait_for_timeout(160)
        page.wait_for_timeout(1200)
        anniversary.click()
        page.wait_for_timeout(4200)
        mark("occasion_picked")
        gen = page.get_by_role("button", name="Generate my reel")
        gen.scroll_into_view_if_needed()
        # hold on the estimate line ("5 photos usually take about 6 minutes."),
        # which is what beat 03's narration points at
        page.wait_for_timeout(6600)
        if args.dry_run:
            gen.wait_for(state="visible", timeout=15_000)
            print("[dry-run] every selector up to Generate resolved. Not submitting.")
            ctx.close()
            browser.close()
            return 0
        gen.click()
        mark("generate_clicked")

        # ── Step 3: the live job ───────────────────────────────────────────
        # The job id lands in the URL as soon as the submission returns. Grab it
        # for the marks file: it is what the reload below relies on, and what
        # GET /reels/jobs/<id> is read from afterwards for the usage numbers.
        job_id = ""
        try:
            page.wait_for_function(
                "() => /^#reel\\/[A-Za-z0-9_-]{8,}$/.test(window.location.hash)",
                timeout=60_000)
            job_id = page.evaluate("() => window.location.hash.slice('#reel/'.length)")
            print(f"[job] {job_id}  url={page.url}", flush=True)
        except Exception as exc:                                  # noqa: BLE001
            print(f"[warn] no #reel/<id> in the URL yet: {exc}", flush=True)
        mark("job_in_url")

        # Beat 04 is cut from here, so hold long enough to fill it BEFORE the
        # reload (PHASE_FLOOR 04-rolling covers generate_clicked -> reload_start).
        page.wait_for_timeout(21_000)          # capture the progress UI moving
        mark("reload_start")

        # ── The reload: the job id in the link is what makes this survivable ──
        # page.reload() (not a new page/context) — a new page would start a new
        # video file and the take would be lost.
        page.reload(wait_until="networkidle")
        resume_copy = page.get_by_text("Picking this reel back up", exact=False)
        try:
            resume_copy.wait_for(state="visible", timeout=25_000)
        except Exception:                                         # noqa: BLE001
            # Take-saving fallback: navigate to the deep link explicitly rather
            # than lose a six-minute live job to a slow rehydrate.
            print("[warn] resume copy did not appear after reload; "
                  "re-entering via the deep link", flush=True)
            if not job_id:
                raise SystemExit("[STOP] reload lost the job and there is no "
                                 "job id to recover it with")
            page.goto(f"{args.base}/#reel/{job_id}", wait_until="networkidle")
            resume_copy.wait_for(state="visible", timeout=60_000)
        page.wait_for_timeout(2200)
        mark("resumed")
        # Hold on the resumed job: the resume line and the "Already in progress"
        # counter are the whole point of beat 05.
        page.wait_for_timeout(9_000)
        for _ in range(4):
            page.mouse.wheel(0, 60)
            page.wait_for_timeout(110)
        page.wait_for_timeout(9_000)
        mark("resume_held")

        # Wait for the result step. The job is live: one concurrent wave,
        # ~6 min for the full five-photo cap.
        result_heading = page.get_by_role("heading", name="Your reel is ready")
        result_heading.wait_for(state="visible", timeout=13 * 60_000)
        page.wait_for_timeout(2500)
        mark("reel_ready")

        # ── Step 4: the reel plays ─────────────────────────────────────────
        # The <video> only mounts once the result step has finished animating in,
        # and it needs its source loaded before play() will do anything. Take 1
        # nudged too early, the element did not exist yet, and the beat recorded
        # a paused player sitting at 0:00. So: wait for the element, wait for it
        # to be readable, THEN play, then prove it is actually advancing.
        page.wait_for_selector("video", state="attached", timeout=60_000)
        page.wait_for_function(
            "() => { const v = document.querySelector('video');"
            "        return v && v.readyState >= 2; }", timeout=90_000)
        page.evaluate(
            """() => { const v = document.querySelector('video');
                       v.muted = true; v.currentTime = 0; return v.play(); }"""
        )
        page.wait_for_timeout(1200)
        playing = page.evaluate(
            "() => { const v = document.querySelector('video');"
            "        return { t: v.currentTime, paused: v.paused, dur: v.duration }; }")
        print(f"[reel] {playing}")
        if playing["paused"] or playing["t"] <= 0:
            print("[warn] the reel did not start playing; beat 05 would be a still")
        mark("reel_playing")
        page.wait_for_timeout(13_000)          # let the reel actually play
        mark("reel_played")

        # ── Provenance + Verify ────────────────────────────────────────────
        prov = page.get_by_role("heading", name="Provenance").first
        prov.scroll_into_view_if_needed()
        page.wait_for_timeout(3000)
        mark("provenance_open")
        for _ in range(8):                      # slow read down the panel
            page.mouse.wheel(0, 100)
            page.wait_for_timeout(170)
        page.wait_for_timeout(3200)
        mark("provenance_scrolled")

        verify = page.get_by_role("button", name="Verify provenance").first
        verify.scroll_into_view_if_needed()
        page.wait_for_timeout(2200)
        verify.click()
        page.wait_for_timeout(9000)
        mark("verified")
        for _ in range(5):
            page.mouse.wheel(0, 100)
            page.wait_for_timeout(170)
        page.wait_for_timeout(8000)
        mark("verified_read")

        total = time.time() - t0
        print(f"[capture] finished in {total:.1f}s", flush=True)

        video = page.video
        vpath = video.path() if video else None
        ctx.close()          # flushes the video file
        browser.close()

    if not vpath or not os.path.exists(vpath):
        raise SystemExit("[STOP] no video was written")
    final = os.path.join(args.out, "journey.webm")
    if os.path.abspath(vpath) != os.path.abspath(final):
        if os.path.exists(final):
            os.remove(final)
        os.replace(vpath, final)
    with open(os.path.join(args.out, "journey.marks.json"), "w", encoding="utf-8") as fh:
        json.dump({"video": "journey.webm", "base": args.base,
                   "uploaded": UPLOAD, "job_id": job_id,
                   "job_url": f"{args.base}/#reel/{job_id}" if job_id else "",
                   "marks": marks}, fh, indent=2)
        fh.write("\n")
    print(f"[ok] {final}  ({os.path.getsize(final) // 1024} KB)")
    print(f"[ok] {os.path.join(args.out, 'journey.marks.json')}")

    at = {m["name"]: m["t"] for m in marks}
    short = []
    print("phase lengths vs. what each beat needs:")
    for beat, a, b, floor in PHASE_FLOOR:
        if a not in at or b not in at:
            short.append(f"{beat}: missing mark {a if a not in at else b}")
            continue
        span = at[b] - at[a]
        ok = span >= floor
        print(f"  [{'OK  ' if ok else 'SHORT'}] {beat:<12} {span:7.2f}s  (needs >= {floor:.1f}s)")
        if not ok:
            short.append(f"{beat}: {span:.2f}s < {floor:.1f}s")
    if short:
        print("\n[STOP] the take is too quick in places; re-shoot with longer dwells:")
        for s in short:
            print(f"  - {s}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
