import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/** Merge Tailwind class names with conflict resolution (shadcn convention). */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}

/** Truncate a hex hash for compact display: `a1b2c3…d4e5f6`. */
export function shortHash(hash: string | null | undefined, edge = 8): string {
  if (!hash) return "—";
  if (hash.length <= edge * 2 + 1) return hash;
  return `${hash.slice(0, edge)}…${hash.slice(-edge)}`;
}

/** Human-readable byte size. */
export function formatBytes(bytes: number | null | undefined): string {
  if (bytes == null || Number.isNaN(bytes)) return "—";
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB"];
  let value = bytes / 1024;
  let i = 0;
  while (value >= 1024 && i < units.length - 1) {
    value /= 1024;
    i += 1;
  }
  return `${value.toFixed(value < 10 ? 1 : 0)} ${units[i]}`;
}

/** Whether a URL can be loaded/streamed in the browser (http/https only). */
export function isPlayableUrl(url: string | null | undefined): url is string {
  return !!url && /^https?:\/\//i.test(url);
}

/** The provider name of the offline deterministic generator. Its clip/reel
 *  bytes are real sealed artifacts but NOT decodable video, so they must never
 *  be handed to a <video> element or the download/share fetch. */
const OFFLINE_PROVIDER = "fake-genblaze";

/** Resolve the URL the player/downloader should actually fetch for a reel.
 *
 *  Returns `null` when the reel is not browser-playable:
 *   - the run was generated by the offline provider (directly, or via the
 *     honest per-request degrade) — deterministic bytes, not decodable video;
 *   - no usable URL exists (legacy backend without `playback_url` and a
 *     non-HTTP storage URL such as `b2://…`).
 *
 *  Otherwise prefers the stable api-relative `playback_url` (the backend
 *  302s to a fresh presigned URL in live mode, or streams bytes offline) and
 *  only falls back to the raw storage URL for legacy backends without it.
 */
export function reelPlaybackUrl(reel: {
  reel_url: string | null;
  playback_url?: string | null;
  provider?: string;
  provider_degraded?: boolean;
}): string | null {
  if (reel.provider_degraded === true || reel.provider === OFFLINE_PROVIDER) return null;
  if (reel.playback_url) return reel.playback_url;
  return isPlayableUrl(reel.reel_url) ? reel.reel_url : null;
}
